version: '2'
services:
  mongo:
    image: mongo
    restart: always

    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
      TZ: "Asia/Taipei"
      
  flask:
    build: ./flask
    links:
      - "mongo"

    expose:
      - "5000"

    volumes:
      - ../src:/home/web
  nginx:
      build: ./nginx
      links:
        - flask
      volumes:
        - "./nginx/log:/var/log/nginx"
        - "../:/usr/share/nginx/html"
      ports:
        - "80:80"

      restart: always